const money=n=>new Intl.NumberFormat('en-QA',{style:'currency',currency:'QAR'}).format(n);
const root=document.documentElement,themeMeta=document.getElementById('theme-color'),THEME_KEY='quickbites_theme';
function setTheme(m){root.setAttribute('data-theme',m);localStorage.setItem(THEME_KEY,m);themeMeta.setAttribute('content',m==='dark'?'#7f0c1e':'#c8102e');document.getElementById('themeToggle').setAttribute('aria-pressed',m==='dark')}
(function(){const s=localStorage.getItem(THEME_KEY);setTheme(s||((matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light'));})();
document.getElementById('themeToggle').addEventListener('click',()=>setTheme(root.getAttribute('data-theme')==='light'?'dark':'light'));
const DATA_MODE='mock';
const CATEGORIES=[{id:'featured',name:'Featured',order:1},{id:'burgers',name:'Burgers',order:2},{id:'chicken',name:'Chicken',order:3},{id:'sides',name:'Sides',order:4},{id:'breakfast',name:'Breakfast',order:5},{id:'desserts',name:'Desserts',order:6},{id:'drinks',name:'Drinks',order:7},{id:'coffee',name:'McCafé',order:8}];
const MENU=[i('Big Classic','Double beef, cheese, special sauce.',21,['featured','burgers']),i('Spicy Supreme','Crispy chicken with heat.',19,['featured','chicken']),i('Loaded Fries','Cheese & smoky bits.',12,['featured','sides']),i('Iced Latte','Bold & smooth over ice.',10,['featured','drinks','coffee']),i('Cheese Burger','Beef, cheese, pickles.',10,['burgers']),i('Double Cheese','Twice the joy.',14,['burgers']),i('BBQ Stack','Smoky & tangy.',18,['burgers']),i('Crispy Chicken','Golden crunch.',15,['chicken']),i('Zesty Chicken','Citrus kick.',16,['chicken']),i('Fries','Thin & crispy.',8,['sides']),i('Onion Rings','Sweet crunch.',9,['sides']),i('Egg Muffin','Egg, cheese, muffin.',9,['breakfast']),i('Hash Browns','Morning crunch.',7,['breakfast','sides']),i('Soft Serve','Vanilla swirl.',6,['desserts']),i('Apple Pie','Warm & cozy.',7.5,['desserts']),i('Coke','Chilled classic.',6,['drinks']),i('Orange Juice','Freshly squeezed vibe.',8,['drinks']),i('Americano','Straight to the point.',9,['coffee']),i('Cappuccino','Foamy goodness.',11,['coffee'])];
function i(n,d,p,c){return{id:n.toLowerCase().replace(/[^a-z0-9]+/g,'-'),name:n,desc:d,price:p,cats:c,imageUrl:'',isFeatured:c.includes('featured')}}
const state={categories:[],items:[],category:'featured',q:'',cart:{}};
const $=s=>document.querySelector(s);const catsEl=$('#cats'),gridEl=$('#grid'),sectionTitle=$('#sectionTitle'),qInput=$('#q');const cartCount=$('#cartCount'),stickyTotal=$('#stickyTotal'),subtot=$('#subtot'),drawer=$('#cartDrawer'),cartItemsEl=$('#cartItems');
init();
async function init(){await loadData();renderCategories();renderGrid();updateTotals();qInput.addEventListener('input',e=>{state.q=e.target.value;renderGrid()})}
async function loadData(){if(DATA_MODE==='mock'){state.categories=[...CATEGORIES].sort((a,b)=>a.order-b.order);state.items=[...MENU];return}if(!window.firebaseDb){console.warn('Firebase not configured; using mock');state.categories=[...CATEGORIES];state.items=[...MENU];return}const{get,ref}=window.firebaseDbFns,db=window.firebaseDb;const sc=await get(ref(db,'menu/categories'));const si=await get(ref(db,'menu/items'));state.categories=sc.exists()?Object.entries(sc.val()).map(([id,v])=>({id,...v})).sort((a,b)=>(a.order||999)-(b.order||999)) : [];state.items=si.exists()?Object.entries(si.val()).map(([id,v])=>({id,...v})) : []}
function renderCategories(){catsEl.innerHTML='';state.categories.forEach(c=>{const b=document.createElement('button');b.className='chip';b.textContent=c.name;b.dataset.id=c.id;b.setAttribute('aria-current',c.id===state.category?'true':'false');b.addEventListener('click',()=>{state.category=c.id;catsEl.querySelectorAll('.chip').forEach(x=>x.setAttribute('aria-current','false'));b.setAttribute('aria-current','true');sectionTitle.textContent=c.name;renderGrid()});catsEl.appendChild(b)})}
function renderGrid(){const t=state.q.trim().toLowerCase();const list=state.items.filter(i=>{const inCat=(state.category==='featured')?(i.isFeatured||(i.cats||[]).includes('featured')):(i.cats||[]).includes(state.category);const matches=t?(i.name.toLowerCase().includes(t)||(i.desc||'').toLowerCase().includes(t)):true;return inCat&&matches});gridEl.innerHTML='';list.forEach(i=>gridEl.appendChild(card(i)));if(!list.length){gridEl.innerHTML='<p style="grid-column:1/-1;color:var(--muted)">No items match your search.</p>'}}
function card(i){const el=document.createElement('article');el.className='card';el.innerHTML=`<div class="img" aria-hidden="true">${i.imageUrl?`<img src="${i.imageUrl}" alt="" style="width:100%;height:100%;object-fit:cover">`:svg()}</div><div class="card-body"><div class="title">${i.name}</div><div class="meta">${i.desc||''}</div><div class="row"><div class="price">${money(i.price)}</div><button class="add" aria-label="Add ${i.name} to cart">Add</button></div></div>`;el.querySelector('.add').addEventListener('click',()=>addToCart(i));return el}
function svg(){return`<svg viewBox="0 0 300 220" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="g1" x1="0" x2="1"><stop offset="0" stop-color="#ffe08a"/><stop offset="1" stop-color="#ffc233"/></linearGradient><linearGradient id="g2" x1="0" x2="1"><stop offset="0" stop-color="#c8102e"/><stop offset="1" stop-color="#a60f27"/></linearGradient></defs><rect width="300" height="220" fill="#fff"/><circle cx="240" cy="40" r="24" fill="url(#g2)" opacity=".9"/><circle cx="40" cy="30" r="16" fill="#ffd76a" opacity=".85"/><g transform="translate(40,60)"><ellipse cx="110" cy="40" rx="100" ry="38" fill="url(#g1)"/><rect x="10" y="60" width="200" height="36" rx="18" fill="#8b5e3c"/><rect x="10" y="92" width="200" height="20" rx="10" fill="#ffcf40"/><rect x="20" y="115" width="180" height="18" rx="9" fill="#823d19"/></g></svg>`}
function addToCart(i){const r=state.cart[i.id]||{...i,qty:0};r.qty+=1;state.cart[i.id]=r;updateTotals();pulse(cartCount)}
function updateTotals(){const items=Object.values(state.cart);const count=items.reduce((n,r)=>n+r.qty,0);const total=items.reduce((s,r)=>s+r.qty*r.price,0);cartCount.textContent=count;stickyTotal.textContent=money(total);subtot.textContent=money(total);renderCartItems()}
function renderCartItems(){const items=Object.values(state.cart);cartItemsEl.innerHTML=items.length?'':'<p style="color:var(--muted);padding:8px 6px">Your cart is empty.</p>';items.forEach(r=>{const row=document.createElement('div');row.className='cart-item';row.innerHTML=`<div class="thumb">${mini()}</div><div><div style="font-weight:800">${r.name}</div><div style="color:var(--muted);font-size:13px">${money(r.price)} each</div></div><div style="text-align:right"><div class="qty" role="group" aria-label="Quantity"><button aria-label="Decrease">−</button><input value="${r.qty}" inputmode="numeric" /><button aria-label="Increase">+</button></div><div style="font-weight:800;margin-top:6px">${money(r.price*r.qty)}</div></div>`;const [m,input,p]=row.querySelectorAll('.qty > *');m.addEventListener('click',()=>changeQty(r.id,-1));p.addEventListener('click',()=>changeQty(r.id,1));input.addEventListener('change',e=>{const v=Math.max(0,parseInt(e.target.value||'0',10));if(v===0) delete state.cart[r.id]; else state.cart[r.id].qty=v; updateTotals()});cartItemsEl.appendChild(row)})}
function mini(){return`<svg width="28" height="28" viewBox="0 0 24 24"><circle cx="12" cy="8" r="7" fill="#ffcd38"/><rect x="2" y="13" width="20" height="6" rx="3" fill="#8b5e3c"/></svg>`}
function changeQty(id,d){const r=state.cart[id];if(!r)return;r.qty+=d;if(r.qty<=0) delete state.cart[id]; updateTotals()}
function pulse(el){el.animate([{transform:'scale(1)'},{transform:'scale(1.15)'},{transform:'scale(1)'}],{duration:260})}
const openCart=()=>drawer.classList.add('open'),closeCart=()=>drawer.classList.remove('open');
document.getElementById('openCart').addEventListener('click',openCart);document.getElementById('openCart2').addEventListener('click',openCart);document.getElementById('closeCart').addEventListener('click',closeCart);
drawer.addEventListener('click',e=>{if(e.target===drawer) closeCart()});document.addEventListener('keydown',e=>{if(e.key==='Escape') closeCart()});
